###
GET http://localhost:3000/items

###
GET http://localhost:3000/items/1

###
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "New Item"
}

###
DELETE http://localhost:3000/items/1

###
PUT http://localhost:3000/items/1
Content-Type: application/json

{
  "name": "Updated Item"
}